### ISSUE TITLE
Android 12+ App crashes with the exception ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by ammar-oker** [Rapsssito/react-native-background-actions#168]
```javascript
const backgroundFetch = async () => {
  try {
    await new Promise(() => {
      runBackgroundFetch()
    });
  } catch (error) {
    // handle error
  }
};

const options = {  /* notification options */ }

const onCloudMessage = async ({ data }) => {
  if (!BackgroundService.isRunning()) {
    try {
      await BackgroundService.start(backgroundFetch, options);
    } catch (e) {
      // handle error
    }
  }
};

```
I have this code above where I run a background task to fetch data whenever a firebase cloud message is received. it's working fine on all android devices below version 12 however it's throwing an error on Android 12+

```
java.lang.RuntimeException: Unable to start service com.asterinet.react.bgactions.RNBackgroundActionsTask@6ff9ef0 with Intent { cmp=com.heyscanner/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.heyscanner/com.asterinet.react.bgactions.RNBackgroundActionsTask
    android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5192)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loopOnce(Looper.java:226)
    android.os.Looper.loop(Looper.java:313)
    android.app.ActivityThread.main(ActivityThread.java:8751)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.heyscanner/com.asterinet.react.bgactions.RNBackgroundActionsTask
    android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
    android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
    android.os.Parcel.readParcelable(Parcel.java:3346)
    android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
    android.os.Parcel.createException(Parcel.java:2422)
    android.os.Parcel.readException(Parcel.java:2405)
    android.os.Parcel.readException(Parcel.java:2347)
    android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:8095)
    android.app.Service.startForeground(Service.java:733)
    com.asterinet.react.bgactions.RNBackgroundActionsTask.onStartCommand(RNBackgroundActionsTask.java:29)
    android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5174)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loopOnce(Looper.java:226)
    android.os.Looper.loop(Looper.java:313)
    android.app.ActivityThread.main(ActivityThread.java:8751)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1955)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1455)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14165)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3648)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3036)


```

I know that it's because of the restrictions on background tasks introduced in Android 12 (API level 31). My question is how to handle the error gracefully without causing the app to crash. Is it possible to ask for the user's permission to bypass these restrictions?

**Comment by smsalert-mobi** [comment]
Having exact same issue.

On stackoverflow there are some details

https://stackoverflow.com/questions/70044393/fatal-android-12-exception-startforegroundservice-not-allowed-due-to-mallows

**Comment by traxx10** [comment]
Same issue on android 12 too

**Comment by Rapsssito** [comment]
@traxx10, @ammar-oker, @smsalert-mobi, I am sorry, but this issue cannot be fixed. There was a new change in Android 12+:

> Apps that target Android 12 (API level 31) or higher can't start foreground services while running in the background

**Comment by apapalillo** [comment]
> @traxx10, @ammar-oker, @smsalert-mobi, I am sorry, but this issue cannot be fixed. There was a new change in Android 12+:

Hi, in other words this would mean `react-native-background-actions` will soon become obsolete. I'm already having tons of these exceptions on my app stacktraces.

I've found we could launch a `Worker` instead of a `Service` on Android 12+ devices, have a look at this answer: https://stackoverflow.com/a/72131422/

**Comment by Rapsssito** [comment]
@apapalillo, `react-native-background-actions` will not become obsolete. The main point was always launching background jobs from the foreground (like in iOS). However, if you want to add new functionality using the `Worker` approach, feel free to send a PR!
