### ISSUE TITLE
Task started but not running on Android (OK on iOS)

### ISSUE THREAD

**Issue by adriendomoison** [Rapsssito/react-native-background-actions#239]
Hi, I'm running into an issue on Android only. The app shows no signs of errors on the JS side. The background notification even shows, but nothing happens, the task function is never called.

```
await BackgroundService.start(
  async () => {
    console.log('I am never called'); // never printed
  },
  {
    taskName: 'Sending Message',
    taskTitle: 'Sending Message',
    taskDesc: 'Sending Message',
    taskIcon: {
      name: 'ic_launcher',
      type: 'mipmap',
    },
  },
);
console.log('Background service started'); // printed
```

In Logcat, I do get an error however:
```
 E  Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
 E  Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
 E  Exception in native call
      java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
       at com.facebook.jni.NativeRunnable.run(Native Method)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
       at java.lang.Thread.run(Thread.java:920)
```

I did set up the `AndroidManifest.xml` according to the documentation (adding permissions and service)

The app is runnin on `React Native 0.75.0`

Any tip would be highly appreciated, thanks!

**Comment by somasekharkakarla** [comment]
can you please the steps for ios. My android is running but not ios.

**Comment by ravindraguptacapgemini** [comment]
It's not starting for me at all, any solutions yet?

**Comment by adriendomoison** [comment]
Switching `newArchEnabled=true` to `newArchEnabled=false` in `android/gradle.properties` allowed the started task to actually run.

I'm not sure if this needs to be documented or if it already exists somewhere I could not find?

**Comment by tohel17** [comment]
@adriendomoison I am facing the same issue it's working fine on iOS with newArchEnabled but in android it fails, Is there any fix to work with newArchEnabled?

**Comment by shovel-kun** [comment]
@tohel17 

AFAIK, you need to wait for RN 0.76.1 (coming in a few days) for the library to work on New Arch.

Source: https://github.com/invertase/react-native-firebase/issues/8091#issuecomment-2440499904

**Comment by ravindraguptacapgemini** [comment]
@tohel17 what about the fix in 0.75.x version?

**Comment by tohel17** [comment]
I am on 0.75.4 still same issues. Looks like you have to wait for 0.76.1

**Comment by adriendomoison** [comment]
To add some more info, a good amount of other packages do not work yet with 0.76.x and it could take several extra weeks for maintainers to deliver the required updates. 

Depending on how many dependencies you have in your current project and how much you are using the newArch already, it could be easier to just stay on 0.75.x and disable newArch.

The decision will highly depends on your circumstances ✌️

**Comment by tohel17** [comment]
It works fine with latest version of RN 0.76.3 with new architecture enabled.

**Comment by ravindraguptacapgemini** [comment]
Can we expect it to start working with any RN 0.75.x release?

**Comment by tohel17** [comment]
@ravindraguptacapgemini Since the issue was on RN side either you have to update to 0.76.1 or use old architecture on 0.75.x version.

**Comment by ravindraguptacapgemini** [comment]
I don't see newer react native version under releases
https://github.com/facebook/react-native/releases
