### ISSUE TITLE
Cannot start react-native server

### ISSUE THREAD

**Issue by unknownFrequency** [Rapsssito/react-native-background-actions#81]
After I do npm install I get the following error:

```
[project]/node_modules/metro-hermes-compiler/src/emhermesc.js:81
          throw ex;
          ^
TypeError: Cannot read property 'lookup' of undefined
    at SendStream.type ([project]/node_modules/send/index.js:845:31)
    at SendStream.send ([project]/node_modules/send/index.js:627:8)
    at onstat ([project]/node_modules/send/index.js:729:10)

If I change the lines in send/index.js to getType() instead of lookup() it is fixed... 
```

send@0.17.1
react-native@0.64.0
react-native-background-actions@2.6.0

Also I have ejected out of Expo

**Comment by Rapsssito** [comment]
@unknownFrequency, it looks like your problem it is not related to this library. Could you please post it in the `send` repository?

**Comment by amalmohann** [comment]
this worked for me `npm start -- --reset-cache`
