### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException "Not allowed to start service Intent" (with solution)

### ISSUE THREAD

**Issue by drash-course** [Rapsssito/react-native-background-actions#91]
Hello !

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-background-actions@2.6.0` for the project I'm working on.

Looking at my Firebase logs I saw this crash:

```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=lu.arhs.fleetback/com.asterinet.react.bgactions.RNBackgroundActionsTask (has extras) }: app is in background uid UidRecord{540e754 u0a52 TPSL bg:+2m27s614ms idle procs:1 proclist:23743, seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
       at android.app.ContextImpl.startService(ContextImpl.java:1611)
       at android.content.ContextWrapper.startService(ContextWrapper.java:677)
       at android.content.ContextWrapper.startService(ContextWrapper.java:677)
       at com.asterinet.react.bgactions.BackgroundActionsModule.start(BackgroundActionsModule.java:53)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:764)
```

Since `reactContext.startService(currentServiceIntent);` can fail, I moved it inside the try / catch block. The caller should get a rejected promise and handle the error gracefully.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/BackgroundActionsModule.java b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/BackgroundActionsModule.java
index 862a220..b43f703 100644
--- a/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/BackgroundActionsModule.java
+++ b/node_modules/react-native-background-actions/android/src/main/java/com/asterinet/react/bgactions/BackgroundActionsModule.java
@@ -45,13 +45,12 @@ public class BackgroundActionsModule extends ReactContextBaseJavaModule {
         try {
             final BackgroundTaskOptions bgOptions = new BackgroundTaskOptions(reactContext, options);
             currentServiceIntent.putExtras(bgOptions.getExtras());
+            // Start the task
+            reactContext.startService(currentServiceIntent);
+            promise.resolve(null);
         } catch (Exception e) {
             promise.reject(e);
-            return;
         }
-        // Start the task
-        reactContext.startService(currentServiceIntent);
-        promise.resolve(null);
     }
 
     @SuppressWarnings("unused")
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Cheers

**Comment by Rapsssito** [comment]
@drash-course, could you create a PR with this fix, please?
